name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # change if your branch is 'master'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Configure Git
        run: |
          git config --global user.name "2300030576"
          git config --global user.email "2300030576@kluniversity.in"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d dist -r https://x-access-token:${GITHUB_TOKEN}@github.com/2300030576/Hospital_14.git
